Fix filter prerelease snapshots
intersystems/ipm pull request #560
Opened 2024-08-30 14:06 UTC by isc-shuliu

Fix #544 (must be used together with https://github.com/intersystems-community/zpm-registry/pull/112)

2024-08-30 14:57 UTC, isc-shuliu commented
@isc-tleavitt 
It won't break. The older zpm registry server will simply ignore these two parameters

2024-09-05 14:57 UTC, isc-shuliu commented
CIs should pass once https://github.com/intersystems-community/zpm-registry/pull/115 gets merged and released. In order to treat `1.0.0-1.m1` as a post-release, use should do `config set SemVerPostRelease 1` and set `includePrerelease` to 1 at the repo level.

2024-09-05 16:52 UTC, isc-tleavitt approved these changes

2024-09-05 17:01 UTC, isc-tleavitt requested changes

2024-09-05 17:01 UTC, isc-tleavitt commented on src/cls/IPM/Repo/Manager.cls
> +			  Set subDirection = $SELECT(+##class(%IPM.Repo.UniversalSettings).GetValue("SemVerPostRelease"): -1, 1: 1)
Nitpick: should call this outside loop.

2024-09-05 17:11 UTC, isc-tleavitt approved these changes

2024-09-16 19:59 UTC, isc-kiyer approved these changes

2024-09-17 15:01 UTC, merged