Allow mapping and unmapping repos & improve zpm error output
intersystems/ipm pull request #663
Opened 2024-12-17 16:20 UTC by isc-shuliu

### Added
- Added support for mapping of repository settings along with, or in addition to, IPM package and routines
- Added functionlity to always unmap repository settings when IPM package and routines are unmapped
- Added support for unmapping of repository settings alone
- Added support for `enable -community` which resets repository settings to default and map IPM along with repo settings globally

### Changed
- Improved error output and instructions in the language extension when "zpm" is run from a namespace without IPM

2024-12-17 17:55 UTC, isc-tleavitt requested changes
Thanks for the super quick turnaround! Since you got this before I had time to update README.md, would you mind taking that on too?

2024-12-17 17:55 UTC, isc-tleavitt commented on CHANGELOG.md
> +### Changed
Nitpick: I'd call this "Fixed" rather than "Changed" (which indicates backwards incompatibility)

2024-12-17 17:55 UTC, isc-tleavitt commented on src/cls/IPM/Main.cls
> +			// Some I4H containers come with %IPM.Main but the "version" command doesn't work ?!
This would probably be those with IPM mapped from HSLIB/HSCUSTOM, on older versions?

2024-12-18 14:05 UTC, isc-eneil approved these changes
@isc-shuliu I noted a couple of typos but the code looks good to me!

2024-12-18 14:05 UTC, isc-eneil commented on src/cls/IPM/Main.cls
> +				Write !, "If you want to map IPM globally, switch to one of the namesapaces above and run: zpm ""enable -map -globally""."
Nit: namespace and namespaces spelling

2024-12-18 17:02 UTC, merged